name: build-openlane-sky130
on: [push]
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    env:
      REPO : misato
      vlnv : misato
    steps:
      - name: Checkout Misato
        uses: actions/checkout@v2
        with:
          path: misato
      - name: Install Amaranth
        run: |
          pip3 install amaranth
          pip3 install amaranth-yosys
          pip3 install git+git://github.com/amaranth-lang/amaranth-boards.git
          pip3 install git+git://github.com/amaranth-lang/amaranth-soc.git
      - name: Build with Openlane
        uses: proppy/ci-fusesoc-action@composite
        with:
          core: misato
          target: sky130
          tool: openlane
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: misato.gds
          path: /home/runner/work/misato/misato/build/misato_0/sky130-openlane/gds/misato_synth_wrapper.gds
